CREATE TABLE [dbo].[User]
(
	Id INT IDENTITY(1,1) NOT NULL,
    Username NVARCHAR(40) NOT NULL,
    Password BINARY(64) NOT NULL,
	Salt UNIQUEIDENTIFIER NOT NULL,
	Email NVARCHAR(40) NOT NULL,
    FirstName NVARCHAR(40) NOT NULL,
    LastName NVARCHAR(40) NOT NULL,
    [RoleId] INT NOT NULL, 
    CONSTRAINT [PK_User_UserID] PRIMARY KEY CLUSTERED (Id ASC), 
  
	

)
