CREATE FUNCTION [dbo].[HashPassword]
(
	@password NVARCHAR(50) NOT NULL,
	@salt UNIQUEIDENTIFIER NOT NULL
)
RETURNS BINARY(64) 
AS
	BEGIN
		RETURN HASHBYTES('SHA2_512', @password + CAST(@salt AS NVARCHAR(36)))
	END
